#!/bin/sh

source_dir=$(readlink -f "$(dirname $0)/../")
files=$(find "$source_dir/cmake" "$source_dir/examples" "$source_dir/src" -regex ".*\.\(h\|c\)" -type f)

IFS=$'\n'
for file in $files; do
    eval "astyle -n --mode=c --style=kr --pad-oper --pad-paren --pad-header \"$file\""
    if [ "$?" != "0" ]; then
        echo "Failed to format \"$file\""
        exit 1
    fi
done
