#define TALLOC_DEBUG
#define TALLOC_EVENTS
#define TALLOC_EXT_DESTRUCTOR
#define TALLOC_EXT
#define TALLOC_REFERENCE
#define TALLOC_UTILS_BUFFER
#define TALLOC_UTILS_DYNARR
#define TALLOC_UTILS_LIST
#define TALLOC_UTILS
#define      TALLOC_MODE TALLOC_EXT || TALLOC_REFERENCE
