#define TALLOC_DEBUG
#define TALLOC_EVENTS
#define TALLOC_EXT_DESTRUCTOR
#define TALLOC_EXT_LENGTH
#define TALLOC_EXT
#define TALLOC_UTILS_BUFFER
/* #undef TALLOC_UTILS_DYNARR */
#define TALLOC_UTILS
