#define TRALLOC_THREADS
#define TRALLOC_LENGTH
#define TRALLOC_EXTENSIONS
#define TRALLOC_DESTRUCTOR
#define TRALLOC_REFERENCE
#define TRALLOC_POOL
#define TRALLOC_FILE
#define TRALLOC_UTILS_BUFFER
#define TRALLOC_UTILS

#define TRALLOC_DEBUG
#define TRALLOC_DEBUG_THREADS
#define TRALLOC_DEBUG_CALLBACKS
#define TRALLOC_DEBUG_STATS
#define TRALLOC_DEBUG_LOG

/* #undef TRALLOC_HAVE_C99_INLINE */
#define TRALLOC_HAVE_BOOL
#define TRALLOC_HAVE_FILE
