/* #undef TRALLOC_THREADS */
/* #undef TRALLOC_LENGTH */
#define TRALLOC_EXTENSIONS
/* #undef TRALLOC_DESTRUCTOR */
#define TRALLOC_REFERENCE
/* #undef TRALLOC_POOL */
/* #undef TRALLOC_FILE */
/* #undef TRALLOC_UTILS_BUFFER */
/* #undef TRALLOC_UTILS */

#define TRALLOC_DEBUG
/* #undef TRALLOC_DEBUG_THREADS */
#define TRALLOC_DEBUG_CALLBACKS
/* #undef TRALLOC_DEBUG_STATS */

/* #undef TRALLOC_HAVE_C99_INLINE */
#define TRALLOC_HAVE_BOOL
#define TRALLOC_HAVE_FILE

#define TRALLOC_SPINLOCK 1
#define TRALLOC_MUTEX    2

/* #undef TRALLOC_DEBUG_LOG */
#define TRALLOC_DEBUG_THREADS_LENGTH   TRALLOC_SPINLOCK
#define TRALLOC_DEBUG_THREADS_CHILDREN TRALLOC_MUTEX
