#define TRALLOC_DEBUG
#define TRALLOC_THREADS
#define TRALLOC_LENGTH
#define TRALLOC_EXTENSIONS
#define TRALLOC_DESTRUCTOR
#define TRALLOC_REFERENCE
#define TRALLOC_POOL
#define TRALLOC_FILE
#define TRALLOC_UTILS_BUFFER
#define TRALLOC_UTILS

#define TRALLOC_HAVE_C99_INLINE
#define TRALLOC_HAVE_BOOL
#define TRALLOC_HAVE_FILE

#define TRALLOC_SPINLOCK 1
#define TRALLOC_MUTEX    2

#define TRALLOC_THREADS_LENGTH                   TRALLOC_SPINLOCK
#define TRALLOC_THREADS_USED_BY_MULTIPLE_THREADS TRALLOC_SPINLOCK
